language: r
sudo: false
cache: packages
notifications:
  slack:
    secure: RVq8x5gkUyJuSyLFxevVEUK4zcgawFVbhsAJkJqDdqDx9RBNMaVuHRLdtjMVg1+rGBw73OWMLqw9RQ/2hwOPvGgBKEveB/K46BfP+t7xGoL0EctzSPFgzMwtHsgc8kFKIa1+kMFo0ZzOEcX+U8VG1YQmj8TbrPoSObZRJJoeZ0Y=
